/** @type {Detox.DetoxConfig} */
module.exports = {
	testRunner: {
		$0: "jest",
		args: {
			config: "e2e/jest.config.js",
			_: ["e2e"],
		},
		jest: {
			setupTimeout: 120000,
		},
	},
	apps: {
		// NOTE: binaryPath / scheme / workspace names below assume the native
		// projects generated by `expo prebuild` for this app (app.json name
		// "my-app" -> sanitized "myapp"). Verify the exact names after the
		// first prebuild and adjust if Expo sanitizes them differently.
		"ios.debug": {
			type: "ios.app",
			binaryPath: "ios/build/Build/Products/Debug-iphonesimulator/myapp.app",
			build:
				"xcodebuild -workspace ios/myapp.xcworkspace -scheme myapp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
		},
		"android.debug": {
			type: "android.apk",
			binaryPath: "android/app/build/outputs/apk/debug/app-debug.apk",
			build:
				"cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
		},
	},
	devices: {
		simulator: {
			type: "ios.simulator",
			device: {
				type: "iPhone 15 Pro",
			},
		},
		emulator: {
			type: "android.emulator",
			device: {
				avdName: "Pixel_7_API_34",
			},
		},
	},
	configurations: {
		"ios.sim.debug": {
			device: "simulator",
			app: "ios.debug",
		},
		"android.emu.debug": {
			device: "emulator",
			app: "android.debug",
		},
	},
};
